server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: public
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  sql:
    init:
      mode: always
      continue-on-error: true
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    default-schema: public
    user: postgres
    password: qwerty